Dev
Major-Project-BE2018SE/polaris-suite-web pull request #3
Opened 2023-04-17 09:29 UTC by Prasiddha777

Landing Page Ui Review

2023-04-17 10:57 UTC, alsongarbuja requested changes

2023-04-17 10:57 UTC, alsongarbuja commented on src/App.tsx
> +      <MasterLayout>
Yo master layout jun xa tyo chai sabai page mah use hudaina hai

use hune bhaneko landing page raw about page mah mattra ho

docs, install, login haru sabai mah arkai layout hunxa pheri

2023-04-17 10:57 UTC, alsongarbuja commented on tailwind.config.cjs
> +        lato: ["Lato", "sans-serif"],
yo hamro lato hoina arko font use garne bhane thim ni tyo use hana hai

2023-04-17 10:57 UTC, alsongarbuja commented on src/components/Navbar.tsx
Yo chai completely change garne parne raixa responsive navbar

2023-04-17 10:57 UTC, alsongarbuja commented on src/components/Footer.tsx
> +          <img src={insta_logo} alt="insta" className="w-7 h-7" />
Yo insta ko logo purai na ako ho ki yestai ho

2023-04-17 10:57 UTC, alsongarbuja commented on src/assets/images/insta_logo.png
Yo insta icon mileko ho??

2023-04-23 10:42 UTC, Prasiddha777 commented on src/components/Navbar.tsx
Changed the layout of the responsive navbar for small screens

2023-04-23 10:59 UTC, Prasiddha777 commented on src/assets/images/insta_logo.png
New Icon downloaded and changed

2023-04-23 11:00 UTC, Prasiddha777 commented on src/components/Footer.tsx
> +          <img src={insta_logo} alt="insta" className="w-7 h-7" />
tyo bahira ko sqaure matra download vayeko rahecha suru maw so now resolved

2023-04-30 04:46 UTC, alsongarbuja approved these changes

2023-04-30 13:49 UTC, Salipa-Gurung approved these changes

2023-04-30 13:50 UTC, merged